---
kind: pipeline
name: test-1-18

steps:
  - name: test
    image: golang:1.18
    commands:
      - export GO111MODULE=on
      - export GOPROXY=https://goproxy.cn
      - go version
      - make test
      - make release
---
kind: pipeline
name: test-1-17

steps:
  - name: test
    image: golang:1.17
    commands:
      - export GO111MODULE=on
      - export GOPROXY=https://goproxy.cn
      - go version
      - make test
      - make release
---
kind: pipeline
name: docker-build

steps:
  - name: docker-build-push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: iceinto/igo
      tags: latest
      insecure: true
...
